const ProductsData = [
    {
      id: 1,
      name: "CrocsFL OL Disney Frozen2 Cg K",
      offer_price: 1200,
      regular_price:1400,
      discount:'10%',
      has_discount:true,
      pickup_from:'Genena Mall',
      is_pickup:true,
      delivery_from:'UK',
      delivery_to:'UK',
      delivery_in:'2 Days',
      category: "Kids",
      image: "images/products/1.png",
      desc: "An apple is a sweet, edible fruit produced by an apple tree (Malus domestica). Apple trees are ... The skin of ripe apples is generally red, yellow, green, pink, or russetted, though many bi- or tri-colored cultivars may be found.",
    },
    {
      id: 2,
      name: "Apple Watch Series 7 45mm Starlight Alu Star Sp Band",
      offer_price: 12550,
      regular_price:14500,
      discount:'35%',
      has_discount:true,
      pickup_from:'Genena Mall',
      is_pickup:true,
      delivery_from:'UK',
      delivery_to:'UK',
      delivery_in:'2 Days',
      category: "Electronics",
      image: "images/products/2.jpg",
      desc: "A banana is an elongated, edible fruit – botanically a berry – produced by several kinds of large herbaceous flowering plants in the genus Musa. In some countries, bananas used for cooking may be called plantains, distinguishing them from dessert bananas.",
    },
    {
      id: 3,
      name: "Adidas Future Icon Dad Cap - Black",
      offer_price: 699,
      regular_price:699,
      discount:0,
      has_discount:false,
      pickup_from:'Genena Mall',
      is_pickup:false,
      delivery_from:'Egypt',
      delivery_to:'Egypt',
      delivery_in:'4 Days',
      category: "Men",
      image: "images/products/3.jpg",
      desc: "The orange is the fruit of various citrus species in the family Rutaceae; it primarily refers to Citrus × sinensis, which is also called sweet orange, to distinguish it from the related Citrus × aurantium, referred to as bitter orange.",
    },
    {
      id: 4,
      name: "Reebok Workout Ready Graphic T-Shirt For Men",
      offer_price: 649,
      regular_price:899,
      discount:'23%',
      has_discount:true,
      pickup_from:'Genena Mall',
      is_pickup:false,
      delivery_from:'Egypt',
      delivery_to:'UK',
      delivery_in:'12 Days',
      category: "Men",
      image: "images/products/4.jpg",
      desc: "Potatoes are a good source of fiber, which can help you lose weight by keeping you full longer. Fiber can help prevent heart disease by keeping cholesterol and blood sugar levels in check. Potatoes are also full of antioxidants that work to prevent diseases and vitamins that help your body function properly.",
    },
    {
      id: 5,
      name: "Levi's Womens Mile High Super Skinny Jeans",
      offer_price: 1599,
      regular_price:1599,
      discount:0,
      has_discount:false,
      pickup_from:'Genena Mall',
      is_pickup:true,
      delivery_from:'UK',
      delivery_to:'UK',
      delivery_in:'2 Days',
      category: "Women",
      image: "images/products/5.png",
      desc: "The onion, also known as the bulb onion or common onion, is a vegetable that is the most widely cultivated species of the genus Allium. The shallot is a botanical variety of the onion. Until 2010, the shallot was classified as a separate species.",
    },
    {
      id: 6,
      name: "Reebok Training Essentials Backpack",
      offer_price: 749,
      regular_price:1400,
      discount:'18%',
      has_discount:true,
      pickup_from:'Genena Mall',
      is_pickup:false,
      delivery_from:'UK',
      delivery_to:'Egypt',
      delivery_in:'10 Days',
      category: "Men",
      image: "images/products/6.jpg",
      desc: "Tomatoes are loaded with a substance called lycopene. It gives them their bright red color and helps protect them from the ultraviolet rays of the sun. In much the same way, it can help protect your cells from damage. Tomatoes also have potassium, vitamins B and E, and other nutrients.",
    },
    {
      id: 7,
      name: "Funny Dino Hoodie - adidas",
      offer_price: 800,
      regular_price:1600,
      discount:'50%',
      has_discount:true,
      pickup_from:'Genena Mall',
      is_pickup:false,
      delivery_from:'Egypt',
      delivery_to:'Egypt',
      delivery_in:'5 Days',
      category: "Kids",
      image: "images/products/7.jpg",
      desc: "Lamb, hogget, and mutton, generically sheep meat, are the meat of domestic sheep , Ovis aries. A sheep in its first year may be a lamb and its meat is additionally lamb. The meat from sheep in their second year is hogget. Older sheep meat is mutton. Generally, “hogget” and “sheep meat” aren’t employed by consumers outside New Zealand, South Africa and Australia.",
    },
    {
      id: 8,
      name: "scarf Shine-1",
      offer_price: 110,
      regular_price:110,
      discount:0,
      has_discount:false,
      pickup_from:'Genena Mall',
      is_pickup:true,
      delivery_from:'UK',
      delivery_to:'UK',
      delivery_in:'2 Days',
      category: "Women",
      image: "images/products/8.png",
      desc: "Beef is that the culinary name for meat from cattle. In prehistoric times, humans hunted aurochs and later domesticated them. Since then, numerous breeds of cattle are bred specifically for the standard or quantity of their meat.",
    },
  ];
  export default ProductsData;
  